CREATE TABLE department
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    total_capacity DOUBLE PRECISION                        NOT NULL,
    description    VARCHAR(255),
    CONSTRAINT pk_department PRIMARY KEY (id)
);

INSERT INTO department (name, total_capacity, description) VALUES
    ('Bloco1', 500.00, 'Responsável arrumar as motos.');

INSERT INTO department (name, total_capacity, description) VALUES
    ('Bloco2', 1500.00, 'Manutençao.');

INSERT INTO department (name, total_capacity, description) VALUES
    ('Bloco3', 800.00, 'Troca de faroes.');
