CREATE TABLE alert
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message         VARCHAR(255),
    level_alert     VARCHAR(255),
    date_time_alert TIMESTAMP WITHOUT TIME ZONE,
    department_id   BIGINT,
    CONSTRAINT pk_alert PRIMARY KEY (id)
);

ALTER TABLE alert
    ADD CONSTRAINT FK_ALERT_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES department (id);


