-- V4: Cria a tabela de vagas de estacionamento e remove a capacidade total estática

-- Remover a coluna total_capacity da tabela department
ALTER TABLE department
DROP COLUMN total_capacity;

-- Criar a tabela parking_space
CREATE TABLE parking_space
(
    parking_space_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code             VARCHAR(255),
    occupied         BOOLEAN,
    department_id    BIGINT,
    CONSTRAINT pk_parkingspace PRIMARY KEY (parking_space_id)
);

-- Adicionar a chave estrangeira para a tabela department
ALTER TABLE parking_space
    ADD CONSTRAINT FK_PARKINGSPACE_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES department (id);

